FROM python:3.7.13-alpine3.14
WORKDIR /usr/src/app

COPY . .
RUN apk add --update --no-cache --virtual .tmp-build-deps \
    gcc libc-dev linux-headers postgresql-dev \
    && apk add libffi-dev && apk add --update nodejs npm \
    && pip install -r requirements.txt && chmod +x launch.sh \
    && adduser -S appuser && chown appuser .

USER appuser

EXPOSE 5555

ENTRYPOINT ["sh", "launch.sh"]

CMD [ "5555" ]