FROM node:16.3.0-alpine as build-stage

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=/api

RUN npm install && npm run build

FROM node:16.3.0-alpine

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/build .

RUN npm install -g serve \
    && adduser -S appuser && chown appuser .

USER appuser

CMD serve -s -l 5000 build
