FROM ubuntu:18.04

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=/api

RUN apt-get update && apt-get install -y curl && \ 
    curl -sL https://deb.nodesource.com/setup_14.x | bash \
    && apt-get install -y nodejs \
    && npm install && npm run build && npm install -g serve \
    && useradd -m appuser && chown appuser . \
    && apt-get purge -y --auto-remove curl \
    && rm -rf /var/lib/apt/lists/* && rm -rf node_modules

USER appuser

CMD serve -s -l 5000 build
