
FROM ubuntu:18.04

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

ENV REQUEST_ORIGIN=http://localhost
ENV PATH /usr/local/go/bin:$PATH

RUN apt-get update && apt-get install -y wget \ 
    && wget -c https://golang.org/dl/go1.16.3.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz \
    && go build && useradd -m appuser

USER appuser

CMD ./server
